#ifndef ENUM_HPP
#define ENUM_HPP

// Instructions
enum {ADD, ADDI, AND, ANDI, CALL, IN, JMP, JMR, JRE, JRS, LOAD, OR, ORI, OUT, RET, SL, SLI, SR, SRI, STORE, SUB, SUBI, XOR, XORI};

// Unités lexicales
enum {UNDEFINED, E_O_F, DATA, CODE, INSTR, REGISTRE, NOMBRE, ID, DEUX_POINTS, VIRGULE, FIN_LIGNE, PLUS, FOIS, MOINS, DIV, EXP, MODULO, PGAUCHE, PDROITE};

#endif
